import Head from "next/head";
import Image from "next/image";
import EmblaCarousel from "../components/emblaCarousel";
import styles from "../styles/Home.module.css";


export default function Home() {


  

  return (
    <div className={styles.container}>
      <Head>
        <title>MAfriculture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <EmblaCarousel />

        <div class="container">
          <div class="description panel blue">
            <div>
              SCROLL DOWN
              <div class="scroll-down">
                <div class="arrow"></div>
              </div>
            </div>
          </div>

          <section class="panel red">ONE</section>
          <section class="panel orange">TWO</section>
          <section class="panel purple">THREE</section>
        </div>
      </div>
    </div>
  );
}
