import Head from "next/head";
import Image from "next/image";
import EmblaCarousel from "../components/emblaCarousel";
import HorizontalScrolling from "../components/horizontalScrolling";
import NewestProduct from "../components/newestProduct";
import styles from "../styles/Home.module.css";

export default function Home() {


  

  return (
    <div className={styles.container}>
      <Head>
        <title>MAfriculture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <EmblaCarousel />

        <NewestProduct/>

        <HorizontalScrolling/>
      </div>
    </div>
  );
}
